
name: NAaaS CI/CD

on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    branches: [main]


jobs:
  build-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.16

    - name: Install dependencies
      run: |
        make install

    - name: Code formatting
      run: |
        make format

    - name: Linting
      run: |
        make lint
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4

  build-push:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.16

    - name: Install dependencies
      run: |
        make install

    - name: Code formatting
      run: |
        make format

    - name: Linting
      run: |
        make lint
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
